config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :books do
  	collection do
  	get 'top'
  	get 'about'
    end
  end

  root 'books#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { in: 1..200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, length: { in: 2..20 }



  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
	def configure_permitted_parameters
    #strong parametersを設定し、usernameを許可
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :password, :password_confirmation, :email) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password, :password_confirmation) }
  end

    def after_sign_in_path_for(resource)
    	user_path(current_user.id)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def about
  end
  
  def index
      @user = current_user
  	  @book = Book.new
  	  @books = Book.all
  end

  def create
  	  @book = Book.new(book_params)
  	  @book.user_id = current_user.id
  	  if @book.save
  	  redirect_to book_path(@book.id), notice: 'You have created book successfully.'
      else @books = Book.all
      render :index
      end
  end

  def show
      @book = Book.new
  	  @book = Book.find(params[:id])
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully.'
      else 
      render :edit
      end
  end

  def destroy
  	  @book = Book.find(params[:id])
  	  @book.destroy
  	  redirect_to books_path
  end

  private
  def book_params
  	  params.require(:book).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      @user = current_user
      @users = User.all
      @book = Book.new
  end

  def show
  	  @user = User.find(params[:id])
      @book = Book.new
  	  @books = @user.books
  end

  def edit
  	  @user = User.find(params[:id])
  end

  def update
  	  @user = User.find(params[:id])
  	  if @user.update(user_params)
  	  redirect_to user_path(@user.id)
      else 
      render "edit"
      end
  end

  private
  def user_params
  	  params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/about.html.erb
<div class="container">
  <div class="row">

  	<div class="col-lg-3">
  	</div>

  	<div class="col-lg-6">

<h1>welcome to <%= icon('fas', 'book') %> Bookers !!</h1><br>

    </div>

  	<div class="col-lg-3">
  	</div>

  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">

  	<div class="col-lg-3">
  	</div>

  	<div class="col-lg-6">

<h1 class="pl-3">Editing Book</h1>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> :</h3>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <h6>Title</h6>
  <%= f.text_field :title, class: "btn-block" %>
  <h6 class="pt-2">Opinion</h6>
  <%= f.text_area :body, class: "btn-block" %><br><br>
  <%= f.submit 'Update Book', class: "btn btn-primary btn-block" %>
<% end %>

<div class="pl-3 pt-2">
  <%= link_to "Show", book_path(@book) %> |
  <%= link_to "Back", books_path %>
 </div>

    </div>

  	<div class="col-lg-3">
  	</div>

  </div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">

    <div class="col-lg-3">

<h2 class="pl-3">User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <table>
    <tr>
      <th>name</th><td><%= @user.name %></td>
    </tr>
    <tr>
      <th>introduction</th><td><%= @user.introduction %></td>
    </tr>
  </table>

  <button type="button" class="btn btn-outline-secondary mt-3 btn-block">
  <%= link_to edit_user_path(@user) do %>
    <%= icon('fas','tools') %> 
  <% end %>
  </button>

<h2 class="pl-3 pt-4">New book</h2>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> :</h3>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <h6>Title</h6>
  <%= f.text_field :title, class: "btn-block" %>
  <h6 class="pt-2">Opinion</h6>
  <%= f.text_area :body, class: "btn-block" %><br><br>
  <%= f.submit 'Create Book', class: "btn btn-primary btn-block" %>
<% end %>

      </div>

      <div class="col-lg-9">

<h2>Books</h2>
<table class="table table-hover">
<thead>
<tr>
  <th></th><th>Title</th><th>Opinion</th>
</tr>
</thead>
<% @books.each do |book| %>
<tr>
  <td>
    <%= link_to user_path(book.user) do %>
      <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "40x40" %>
    <% end %>
  </td>
  <td><%= link_to book.title, book_path(book) %></td>
  <td><%= book.body %></td>
</tr>
<% end %>

</table>

    </div>

  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">

    <div class="col-lg-3">

<h2 class="pl-3">User info</h2>
  <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <table>
    <tr>
      <th>name</th><td><%= @book.user.name %></td>
    </tr>
    <tr>
      <th>introduction</th><td><%= @book.user.introduction %></td>
    </tr>
  </table>

  <% if @book.user == current_user %>
  <button type="button" class="btn btn-outline-secondary mt-3 btn-block">
  <%= link_to edit_user_path(@book.user) do %>
    <%= icon('fas','tools') %> 
  <% end %>
  </button>
  <% else %>
    <button type="button" class="btn btn-outline-secondary mt-3 btn-block">
  <%= link_to user_path(current_user) do %>
    <%= icon('fas','tools') %> 
  <% end %>
  </button>
  <% end %>

<h2 class="pl-3 pt-4">New book</h2>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> :</h3>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <h6>Title</h6>
  <%= f.text_field :title, class: "btn-block" %>
  <h6 class="pt-2">Opinion</h6>
  <%= f.text_area :body, class: "btn-block" %><br>
  <%= f.submit 'Create Book', class: "btn btn-primary btn-block" %>
<% end %>

      </div>

      <div class="col-lg-9">

<h2>Book detail</h2>
<table class="table table-sm">
<tr>
  <td>
    <%= link_to user_path(@book.user) do %>
    <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "40x40" %>
    <% end %><br>
    <%= link_to @book.user.name, user_path(@book.user) %>
  </td>
  <td><%= link_to @book.title, book_path(@book)%></td>
  <td><%= @book.body %></td>
  <% if @book.user == current_user %>
    <td class="btn btn-success btn-sm">
      <%= link_to "Edit", edit_book_path(@book) %>     
    </td>
  <% end %> 
  <td></td>
  <% if @book.user == current_user %>
    <td class="btn btn-danger btn-sm">
      <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？" %>
    </td>
  <% end %> 
</tr>

</table>

   </div>

  </div>
</div>

app/views/books/top.html.erb
<div class="container">
  <div class="row">

  	<div class="col-lg-3">
  	</div>

  	<div class="col-lg-6">

<h1>welcome to <%= icon('fas', 'book') %> Bookers !!</h1><br>

<p>In <%= icon('fas', 'book') %> Bookers,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>

<button type="button" class="btn btn-outline-secondary bg-warning mt-1 btn-block">
  <%= link_to "Log in", new_user_session_path %>
</button>
<button type="button" class="btn btn-outline-secondary bg-success btn-block">
  <%= link_to "Sign Up", new_user_registration_path %>
</button>

    </div>

  	<div class="col-lg-3">
  	</div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-fixed-top navbar-expand-sm text-light bg-dark pt-3 pb-3 mb-3">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
        </nav>
        <nav class="nav navbar-nav navbar-right">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
            <li class="nav-item activ">
              <%= link_to user_path(current_user.id) do %>
                <%= icon('fas','home') %><span class="ml-2">Home</span>
              <% end %>
            </li>
            <li class="nav-item ml-4">
              <%= link_to users_path do %>
                <%= icon('fas','user') %><span class="ml-2">Users</span>
              <% end %>
            </li>
            <li class="nav-item ml-4">
              <%= link_to books_path do %>
                <%= icon('fas','book') %><span class="ml-2">Books</span>
              <% end %>
            </li>
            <li class="nav-item ml-4">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= icon('fas','sign-out-alt') %><span class="ml-2">logout</span>
              <% end %>
            </li>
            <% else %>
            <li class="nav-item activ">
              <%= link_to "/books/top" do %>
                <%= icon('fas','home') %><span class="ml-2">Home</span>
              <% end %>
            </li>
            <li class="nav-item ml-4">
              <%= link_to about_books_path do %>
                <%= icon('fas','paperclip') %><span class="ml-2">About</span>
              <% end %>
            </li>
            <li class="nav-item ml-4">
              <%= link_to new_user_registration_path do %>
                <%= icon('fas','edit') %><span class="ml-2">sign up</span>
              <% end %>
            </li>
            <li class="nav-item ml-4">
              <%= link_to new_user_session_path do %>
                <%= icon('fas','sign-in-alt') %><span class="ml-2">login</span>
              <% end %>
            </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <h3><%= pluralize(@user.errors.count, "error") %> :</h3>
    <% @user.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
    <h6 class="mt-4">Name</h6>
    <%= f.text_field :name %>
    <h6 class="mt-4">Image</h6>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    <h6 class="mt-4">Introduction</h6>
    <%= f.text_area :introduction %><br>
    <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.hrml.erb
<div class="container">
  <div class="row">

    <div class="col-lg-3">

<h2 class="pl-3">User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <table>
    <tr>
      <th>name</th><td><%= @user.name %></td>
    </tr>
    <tr>
      <th>introduction</th><td><%= @user.introduction %></td>
    </tr>
  </table>

  <button type="button" class="btn btn-outline-secondary mt-3 btn-block">
  <%= link_to edit_user_path(@user) do %>
    <%= icon('fas','tools') %> 
  <% end %>
  </button>

<h2 class="pl-3 pt-4">New book</h2>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> :</h3>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <h6>Title</h6>
  <%= f.text_field :title, class: "btn-block" %>
  <h6 class="pt-2">Opinion</h6>
  <%= f.text_area :body, class: "btn-block" %><br>
  <%= f.submit 'Create Book', class: "btn btn-primary btn-block" %>
<% end %>

      </div>

      <div class="col-lg-9">

<h2>Users</h2>
<table class="table table-hover">
<thead>
<tr>
  <th>image</th><th>name</th><th></th>
</tr>
</thead>
<% @users.each do |user| %>
<tr>
  <td>
  	<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "40x40" %>
  </td>
  <td><%=  user.name %></td>
  <td><%= link_to "show", user_path(user) %></td>
</tr>
<% end %>

</table>

    </div>

  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-lg-3">

<h2 class="pl-3">User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <table>
    <tr>
      <th>name</th><td><%= @user.name %></td>
    </tr>
    <tr>
      <th>introduction</th><td><%= @user.introduction %></td>
    </tr>
  </table>

  <button type="button" class="btn btn-outline-secondary mt-3 btn-block">
  <%= link_to edit_user_path(@user) do %>
    <%= icon('fas','tools') %> 
  <% end %>
  </button>

<h2 class="pl-3 pt-4">New book</h2>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> :</h3>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <h6>Title</h6>
  <%= f.text_field :title, class: "btn-block" %>
  <h6 class="pt-2">Opinion</h6>
  <%= f.text_area :body, class: "btn-block" %><br>
  <%= f.submit 'Create Book', class: "btn btn-primary btn-block" %>
<% end %>

      </div>

      <div class="col-lg-9">

<h2>Users</h2>
<table class="table">
<thead>
<tr>
  <th>image</th><th>name</th><th></th>
</tr>
</thead>
<% @users.each do |user| %>
<tr>
  <td>
  	<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "40x40" %>
  </td>
  <td><%=  user.name %></td>
  <td><%= link_to "show", user_path(user) %></td>
</tr>
<% end %>

</table>

    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-3">

<h2 class="pl-3">User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <table>
    <tr>
      <th>name</th><td><%= @user.name %></td>
    </tr>
    <tr>
      <th>introduction</th><td><%= @user.introduction %></td>
    </tr>
  </table>

  <button type="button" class="btn btn-outline-secondary mt-3 btn-block">
  <%= link_to edit_user_path(@user) do %>
    <%= icon('fas','tools') %> 
  <% end %>
  </button>

<h2 class="pl-3 pt-4">New book</h2>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> :</h3>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <h6>Title</h6>
  <%= f.text_field :title, class: "btn-block" %>
  <h6 class="pt-2">Opinion</h6>
  <%= f.text_area :body, class: "btn-block" %><br>
  <%= f.submit 'Create Book', class: "btn btn-primary btn-block" %>
<% end %>

      </div>

      <div class="col-xs-9">

<h2>Books</h2>
<table class="table table-hover">
<thead>
<tr>
  <th></th><th>Title</th><th>Opinion</th>
</tr>
</thead>
<% @books.each do |book| %>
<tr>
  <td>
  	<%= link_to user_path(@user) do %>
  	<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: "40x40" %>
  	<% end %>
  </td>
  <td><%= link_to book.title, book_path(book) %></td>
  <td><%= book.body %></td>
</tr>
<% end %>

</table>

    </div>

  </div>
</div>